name: Amazon sagemaker endtoend pipeline

on:
  push:
    branches:
      - main # triggers when code is pushed to main branch
  workflow_dispatch: # for manual trigger

jobs:
  trigger-sagemaker-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repositories
      uses: actions/Checkout@v4

    - name: Set up python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: configure AWS cloud credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: install runtime requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt


